apiVersion: apps/v1
kind: Deployment
metadata:
  name: weyesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weyesk
  template:
    metadata:
      labels:
        app: weyesk
    spec:
      containers:
      - image: okteto.dev/weyesk:latest
        name: weyesk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6271009e-5b37-4eb9-8762-82cf9422da05"
        - name: Vless_Path
          value: "/bjnd"
        - name: Vmess_UUID
          value: "6271009e-5b37-4eb9-8762-82cf9422da05"
        - name: Vmess_Path
          value: "/tboss"
        - name: Share_Path
          value: "/shareg3kl"
