apiVersion: apps/v1
kind: Deployment
metadata:
  name: majim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: majim
  template:
    metadata:
      labels:
        app: majim
    spec:
      containers:
      - image: okteto.dev/majim:latest
        name: majim
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ea2fbf82-4f5e-4aa9-9265-3f02a328dbcc"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "ea2fbf82-4f5e-4aa9-9265-3f02a328dbcc"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
