apiVersion: apps/v1
kind: Deployment
metadata:
  name: nieim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nieim
  template:
    metadata:
      labels:
        app: nieim
    spec:
      containers:
      - image: okteto.dev/nieim:latest
        name: nieim
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "86af63cd-f656-4ac7-bddc-3a39b0c3d0cf"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "86af63cd-f656-4ac7-bddc-3a39b0c3d0cf"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
