apiVersion: apps/v1
kind: Deployment
metadata:
  name: jrigr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jrigr
  template:
    metadata:
      labels:
        app: jrigr
    spec:
      containers:
      - image: okteto.dev/jrigr:latest
        name: jrigr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "4e75ae03-e1fb-4603-b0a5-6c7cb7ce0a32"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "4e75ae03-e1fb-4603-b0a5-6c7cb7ce0a32"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
