apiVersion: apps/v1
kind: Deployment
metadata:
  name: kknzk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kknzk
  template:
    metadata:
      labels:
        app: kknzk
    spec:
      containers:
      - image: okteto.dev/kknzk:latest
        name: kknzk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "3bc8f9d8-5cf5-4f0a-aa30-3351692d6c38"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "3bc8f9d8-5cf5-4f0a-aa30-3351692d6c38"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
