apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbjgt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbjgt
  template:
    metadata:
      labels:
        app: mbjgt
    spec:
      containers:
      - image: okteto.dev/mbjgt:latest
        name: mbjgt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "508aa9b1-4d56-4ae0-ad6d-f05edc39383f"
        - name: Vless_Path
          value: "/qergh"
        - name: Vmess_UUID
          value: "508aa9b1-4d56-4ae0-ad6d-f05edc39383f"
        - name: Vmess_Path
          value: "/zvbge"
        - name: Share_Path
          value: "/sharegjhot"
