apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgfjd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jgfjd
  template:
    metadata:
      labels:
        app: jgfjd
    spec:
      containers:
      - image: okteto.dev/jgfjd:latest
        name: jgfjd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ad2f0a02-c670-4ead-8e35-51702a01fdd8"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "ad2f0a02-c670-4ead-8e35-51702a01fdd8"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
