apiVersion: apps/v1
kind: Deployment
metadata:
  name: ythtry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ythtry
  template:
    metadata:
      labels:
        app: ythtry
    spec:
      containers:
      - image: okteto.dev/ythtry:latest
        name: ythtry
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "4fdfeb42-fe91-4e4b-9027-1fe46f272add"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "4fdfeb42-fe91-4e4b-9027-1fe46f272add"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
