apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbhds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbhds
  template:
    metadata:
      labels:
        app: lbhds
    spec:
      containers:
      - image: okteto.dev/lbhds:latest
        name: lbhds
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6fc682a0-27b0-42ff-ba2b-8bb206eeafbd"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "6fc682a0-27b0-42ff-ba2b-8bb206eeafbd"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
