apiVersion: apps/v1
kind: Deployment
metadata:
  name: linew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linew
  template:
    metadata:
      labels:
        app: linew
    spec:
      containers:
      - image: okteto.dev/linew:latest
        name: linew
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "1c9ea807-9a75-475b-9ec7-5225e6f1e6b9"
        - name: Vless_Path
          value: "/bjnd"
        - name: Vmess_UUID
          value: "1c9ea807-9a75-475b-9ec7-5225e6f1e6b9"
        - name: Vmess_Path
          value: "/tboss"
        - name: Share_Path
          value: "/shareg3kl"
