apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljgda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ljgda
  template:
    metadata:
      labels:
        app: ljgda
    spec:
      containers:
      - image: okteto.dev/ljgda:latest
        name: ljgda
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "89b2f030-14e6-4b73-a71b-09efacfc6655"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "89b2f030-14e6-4b73-a71b-09efacfc6655"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
