apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcegd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcegd
  template:
    metadata:
      labels:
        app: hcegd
    spec:
      containers:
      - image: okteto.dev/hcegd:latest
        name: hcegd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8e437d15-4126-4321-a74d-52fb74be44de"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "8e437d15-4126-4321-a74d-52fb74be44de"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
