apiVersion: apps/v1
kind: Deployment
metadata:
  name: milsy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milsy
  template:
    metadata:
      labels:
        app: milsy
    spec:
      containers:
      - image: okteto.dev/milsy:latest
        name: milsy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "9488d576-cb32-442d-ad46-f53ae335958c"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "9488d576-cb32-442d-ad46-f53ae335958c"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
