apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldhrj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldhrj
  template:
    metadata:
      labels:
        app: ldhrj
    spec:
      containers:
      - image: okteto.dev/ldhrj:latest
        name: ldhrj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b8333f95-cff9-42e5-8965-6d342cecba2b"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "b8333f95-cff9-42e5-8965-6d342cecba2b"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
