apiVersion: apps/v1
kind: Deployment
metadata:
  name: obhfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obhfs
  template:
    metadata:
      labels:
        app: obhfs
    spec:
      containers:
      - image: okteto.dev/obhfs:latest
        name: obhfs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "910717e0-e887-4112-8386-30990140851b"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "910717e0-e887-4112-8386-30990140851b"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
