apiVersion: apps/v1
kind: Deployment
metadata:
  name: bencr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bencr
  template:
    metadata:
      labels:
        app: bencr
    spec:
      containers:
      - image: okteto.dev/bencr:latest
        name: bencr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b2ed6ef0-e5d9-49c7-bede-12b1fe186c50"
        - name: Vless_Path
          value: "/qergh"
        - name: Vmess_UUID
          value: "b2ed6ef0-e5d9-49c7-bede-12b1fe186c50"
        - name: Vmess_Path
          value: "/zvbge"
        - name: Share_Path
          value: "/sharegjhot"
