apiVersion: apps/v1
kind: Deployment
metadata:
  name: hertoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hertoo
  template:
    metadata:
      labels:
        app: hertoo
    spec:
      containers:
      - image: okteto.dev/hertoo:latest
        name: hertoo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "cc85b6cc-ecbd-4904-9dd8-c93baf87ffdc"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "cc85b6cc-ecbd-4904-9dd8-c93baf87ffdc"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
