apiVersion: apps/v1
kind: Deployment
metadata:
  name: admi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admi
  template:
    metadata:
      labels:
        app: admi
    spec:
      containers:
      - image: okteto.dev/admi:latest
        name: admi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8b35e48e-c638-41d9-9584-de02810e1d8c"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "8b35e48e-c638-41d9-9584-de02810e1d8c"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
