apiVersion: apps/v1
kind: Deployment
metadata:
  name: lszx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lszx
  template:
    metadata:
      labels:
        app: lszx
    spec:
      containers:
      - image: okteto.dev/lszx:latest
        name: lszx
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b9c32c54-3c59-4430-83cb-140630205fb3"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "b9c32c54-3c59-4430-83cb-140630205fb3"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
