apiVersion: apps/v1
kind: Deployment
metadata:
  name: ythgrg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ythgrg
  template:
    metadata:
      labels:
        app: ythgrg
    spec:
      containers:
      - image: okteto.dev/ythgrg:latest
        name: ythgrg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "a2745297-792f-4c7e-b0e7-5baef3cc7d63"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "a2745297-792f-4c7e-b0e7-5baef3cc7d63"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
