apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdhjk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdhjk
  template:
    metadata:
      labels:
        app: fdhjk
    spec:
      containers:
      - image: okteto.dev/fdhjk:latest
        name: fdhjk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "44924cd9-be93-4ae7-ac74-46cdda7b86e9"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "44924cd9-be93-4ae7-ac74-46cdda7b86e9"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
