apiVersion: apps/v1
kind: Deployment
metadata:
  name: trthu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trthu
  template:
    metadata:
      labels:
        app: trthu
    spec:
      containers:
      - image: okteto.dev/trthu:latest
        name: trthu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8896f149-901b-497d-b188-88d3bec2de03"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "8896f149-901b-497d-b188-88d3bec2de03"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
