apiVersion: apps/v1
kind: Deployment
metadata:
  name: joht
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joht
  template:
    metadata:
      labels:
        app: joht
    spec:
      containers:
      - image: okteto.dev/joht:latest
        name: joht
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8c364120-17e0-4313-8a9a-6e49b22019eb"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "8c364120-17e0-4313-8a9a-6e49b22019eb"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
