apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkhyf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jkhyf
  template:
    metadata:
      labels:
        app: jkhyf
    spec:
      containers:
      - image: okteto.dev/jkhyf:latest
        name: jkhyf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ea3d6922-12bf-485a-822b-4ad74bca663c"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "ea3d6922-12bf-485a-822b-4ad74bca663c"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
