apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbror
  template:
    metadata:
      labels:
        app: nbror
    spec:
      containers:
      - image: okteto.dev/nbror:latest
        name: nbror
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "57c52037-df92-403f-8c41-56696358552f"
        - name: Vless_Path
          value: "/qergh"
        - name: Vmess_UUID
          value: "57c52037-df92-403f-8c41-56696358552f"
        - name: Vmess_Path
          value: "/zvbge"
        - name: Share_Path
          value: "/sharegjhot"
