apiVersion: apps/v1
kind: Deployment
metadata:
  name: ringt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ringt
  template:
    metadata:
      labels:
        app: ringt
    spec:
      containers:
      - image: okteto.dev/ringt:latest
        name: ringt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "967e9443-8a5c-4b9b-b741-61a7d26e500a"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "967e9443-8a5c-4b9b-b741-61a7d26e500a"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
