apiVersion: apps/v1
kind: Deployment
metadata:
  name: dafg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dafg
  template:
    metadata:
      labels:
        app: dafg
    spec:
      containers:
      - image: okteto.dev/dafg:latest
        name: dafg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "9121295a-5e2a-494c-a30c-e35a85437591"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "9121295a-5e2a-494c-a30c-e35a85437591"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
