apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdgx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdgx
  template:
    metadata:
      labels:
        app: hdgx
    spec:
      containers:
      - image: okteto.dev/hdgx:latest
        name: hdgx
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "326136ab-707a-4b66-a9d1-46d076df7c9c"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "326136ab-707a-4b66-a9d1-46d076df7c9c"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
