apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwbjr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rwbjr
  template:
    metadata:
      labels:
        app: rwbjr
    spec:
      containers:
      - image: okteto.dev/rwbjr:latest
        name: rwbjr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8019ae93-0778-4ba1-81b7-3dc29a9b20cb"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "8019ae93-0778-4ba1-81b7-3dc29a9b20cb"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
