apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyent
  template:
    metadata:
      labels:
        app: kyent
    spec:
      containers:
      - image: okteto.dev/kyent:latest
        name: kyent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f5249d33-c97e-4bda-a55f-e4cbbf217a18"
        - name: Vless_Path
          value: "/bjnd"
        - name: Vmess_UUID
          value: "f5249d33-c97e-4bda-a55f-e4cbbf217a18"
        - name: Vmess_Path
          value: "/tboss"
        - name: Share_Path
          value: "/shareg3kl"
