apiVersion: apps/v1
kind: Deployment
metadata:
  name: leety
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leety
  template:
    metadata:
      labels:
        app: leety
    spec:
      containers:
      - image: okteto.dev/leety:latest
        name: leety
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "cbf04ac4-0b64-44b5-9da7-b1665885af42"
        - name: Vless_Path
          value: "/qergh"
        - name: Vmess_UUID
          value: "cbf04ac4-0b64-44b5-9da7-b1665885af42"
        - name: Vmess_Path
          value: "/zvbge"
        - name: Share_Path
          value: "/sharegjhot"
