apiVersion: apps/v1
kind: Deployment
metadata:
  name: xwnj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xwnj
  template:
    metadata:
      labels:
        app: xwnj
    spec:
      containers:
      - image: okteto.dev/xwnj:latest
        name: xwnj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "868288eb-0a86-4c2c-ae68-3afd130ca0a9"
        - name: Vless_Path
          value: "/bjnd"
        - name: Vmess_UUID
          value: "868288eb-0a86-4c2c-ae68-3afd130ca0a9"
        - name: Vmess_Path
          value: "/tboss"
        - name: Share_Path
          value: "/shareg3kl"
