apiVersion: apps/v1
kind: Deployment
metadata:
  name: rjhtjo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rjhtjo
  template:
    metadata:
      labels:
        app: rjhtjo
    spec:
      containers:
      - image: okteto.dev/rjhtjo:latest
        name: rjhtjo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "848cc0a7-9c87-4bcc-855c-35202b51d5e3"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "848cc0a7-9c87-4bcc-855c-35202b51d5e3"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
