apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttghg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttghg
  template:
    metadata:
      labels:
        app: ttghg
    spec:
      containers:
      - image: okteto.dev/ttghg:latest
        name: ttghg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "162738b6-e156-4930-b6a9-2bb242bb0a97"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "162738b6-e156-4930-b6a9-2bb242bb0a97"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
