apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojjgdh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ojjgdh
  template:
    metadata:
      labels:
        app: ojjgdh
    spec:
      containers:
      - image: okteto.dev/ojjgdh:latest
        name: ojjgdh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "1de3fb7b-eaaa-41aa-b2b5-234e8f6efe20"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "1de3fb7b-eaaa-41aa-b2b5-234e8f6efe20"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
