apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljhfcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ljhfcs
  template:
    metadata:
      labels:
        app: ljhfcs
    spec:
      containers:
      - image: okteto.dev/ljhfcs:latest
        name: ljhfcs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "fbec95f0-e75d-45b0-a7f3-60fe95b1f1c5"
        - name: Vless_Path
          value: "/3rty"
        - name: Vmess_UUID
          value: "fbec95f0-e75d-45b0-a7f3-60fe95b1f1c5"
        - name: Vmess_Path
          value: "/6yui"
        - name: Share_Path
          value: "/share246"
