apiVersion: apps/v1
kind: Deployment
metadata:
  name: horsx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horsx
  template:
    metadata:
      labels:
        app: horsx
    spec:
      containers:
      - image: okteto.dev/horsx:latest
        name: horsx
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "af1ae882-a194-4afd-bf8d-34b979cc137d"
        - name: Vless_Path
          value: "/bjnd"
        - name: Vmess_UUID
          value: "af1ae882-a194-4afd-bf8d-34b979cc137d"
        - name: Vmess_Path
          value: "/tboss"
        - name: Share_Path
          value: "/shareg3kl"
