apiVersion: apps/v1
kind: Deployment
metadata:
  name: grren
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grren
  template:
    metadata:
      labels:
        app: grren
    spec:
      containers:
      - image: okteto.dev/grren:latest
        name: grren
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "bef362e4-cbae-4233-9a24-4c0052385d39"
        - name: Vless_Path
          value: "/hytu6"
        - name: Vmess_UUID
          value: "bef362e4-cbae-4233-9a24-4c0052385d39"
        - name: Vmess_Path
          value: "/ttyio"
        - name: Share_Path
          value: "/sharetbv"
