apiVersion: apps/v1
kind: Deployment
metadata:
  name: bashe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bashe
  template:
    metadata:
      labels:
        app: bashe
    spec:
      containers:
      - image: okteto.dev/bashe:latest
        name: bashe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b2903d29-7b4d-4a5e-ab1c-df3ce60c7a28"
        - name: Vless_Path
          value: "/qergh"
        - name: Vmess_UUID
          value: "b2903d29-7b4d-4a5e-ab1c-df3ce60c7a28"
        - name: Vmess_Path
          value: "/zvbge"
        - name: Share_Path
          value: "/sharegjhot"
