apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dorler
  template:
    metadata:
      labels:
        app: dorler
    spec:
      containers:
      - image: okteto.dev/dorler:latest
        name: dorler
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "617f8057-fb6e-409a-a6e2-0580658fa67b"
        - name: Vless_Path
          value: "/hyjv"
        - name: Vmess_UUID
          value: "617f8057-fb6e-409a-a6e2-0580658fa67b"
        - name: Vmess_Path
          value: "/tsdf1"
        - name: Share_Path
          value: "/share6gh"
