apiVersion: v1
kind: Service
metadata:
  name: grren
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: grren"
    port: 8080
  selector:
    app: grren
